name: Build

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: vvakame/review:5.9

    steps:
    - uses: actions/checkout@v4.2.2

    - name: setup ruby
      run: bundle install

    - name: build
      run: bundler exec rake pdf
