name: Build

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: vvakame/review:5.9

    steps:
    - uses: actions/checkout@v4.2.2

    - name: install dependencies
      run: |
        sudo apt update -y
        sudo apt install -y texlive-science

    - uses: ruby/setup-ruby@v1.206.0
      with:
        bundler-cache: true

    - name: build
      run: bundler exec rake pdf
